#!/bin/bash
#
# A simple framework for testing the bn scripts
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' expected_return_value 'stdin text' 'expected stdout' 'expected stderr'
#
# Some example test cases are given. You should add more test cases.
#
# Sam Scott, McMaster University, 2024


# GLOBALS: tc = test case number, fails = number of failed cases
declare -i tc=0
declare -i fails=0

############################################
# Run a single test. Runs a given command 3 times
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = expected return value
#         $3 = standard input text to send
#         $4 = expected stdout
#         $5 = expected stderr
# RETURNS: 0 = success, 1 = bad return, 
#          2 = bad stdout, 3 = bad stderr
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local RETURN=$2
	local STDIN=$3
    local STDOUT=$4
    local STDERR=$5

    # CHECK RETURN VALUE
    $COMMAND <<< "$STDIN" >/dev/null 2>/dev/null
    local A_RETURN=$?

    if [[ "$A_RETURN" != "$RETURN" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected Return: $RETURN"
        echo "   Actual Return: $A_RETURN"
        fails=$fails+1
        return 1
    fi

    # CHECK STDOUT
    local A_STDOUT=$($COMMAND <<< "$STDIN" 2>/dev/null)

    if [[ "$STDOUT" != "$A_STDOUT" ]] && [[ "$STDERR" != "test" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDOUT: $STDOUT"
        echo "   Actual STDOUT: $A_STDOUT"
        fails=$fails+1
        return 2
    fi
    
    # CHECK STDERR
    local A_STDERR=$($COMMAND <<< "$STDIN" 2>&1 >/dev/null)

    if [[ "$STDERR" != "$A_STDERR" ]] && [[ "$STDERR" != "test" ]] ; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDERR: $STDERR"
        echo "   Actual STDERR: $A_STDERR"
        fails=$fails+1
        return 3
    fi
    
    # SUCCESS
    echo "Test $tc Passed"
    return 0
}
##########################################
# EXAMPLE TEST CASES
##########################################

#invalid level
test './playWords' 1 '4\n5\n' 'Enter wordle size between 5 and 8 letters' 'Invalid word size'



test './playtest' 1 '5 -5' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)' 'Invalid number of attempts'
test './playtest' 1 '' 'Enter wordle size between 5 and 8 letters' 'Invalid entry'
test './playtest' 1 '5' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)' 'Invalid entry'
test './playtest' 0 '5 1' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)
Enter guess
Answer was' 'test'


test './playtest' 0 '5 1 aljdklasjdlkasj hello' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)
Enter guess
Invalid word. Try again
hello
You are out of attempts
Answer was' 'test'
test './playtest' 0 '6 1 aloha' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)
Enter guess
Invalid word. Try again
aloha
You are out of attempts
Answer was' 'test'
test './playtest' 0 '7 1 players' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)
Enter guess
Invalid word. Try again
players
You are out of attempts
Answer was' 'test'
test './playtest' 0 '8 1 absolute' 'Enter wordle size between 5 and 8 letters
Enter number of attempts you have (1-10)
Enter guess
Invalid word. Try again
absolute
You are out of attempts
Answer was' 'test'
test './playtest --help' 0 '' 'Usage: Help Function
Welcome to Words, a level-based guessing game.
You will:
  - Enter a word size between 5 and 8 letters.
  - Enter the number of attempts you prefer (1–10).
  - Guess words of the correct length.
  - Words must exist in the dictionary.
  - Colours:
       Green  = correct letter and position
       Yellow = letter exists but wrong position in word
       Red    = letter does not exist in word' ''

#return code
exit $fails
