#!/bin/bash
#
# A simple framework for testing the bn scripts
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' expected_return_value 'stdin text' 'expected stdout' 'expected stderr'
#
# Some example test cases are given. You should add more test cases.
#
# Sam Scott, McMaster University, 2024


# GLOBALS: tc = test case number, fails = number of failed cases
declare -i tc=0
declare -i fails=0

############################################
# Run a single test. Runs a given command 3 times
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = expected return value
#         $3 = standard input text to send
#         $4 = expected stdout
#         $5 = expected stderr
# RETURNS: 0 = success, 1 = bad return, 
#          2 = bad stdout, 3 = bad stderr
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local RETURN=$2
	local STDIN=$3
    local STDOUT=$4
    local STDERR=$5

    # CHECK RETURN VALUE
    $COMMAND <<< "$STDIN" >/dev/null 2>/dev/null
    local A_RETURN=$?

    if [[ "$A_RETURN" != "$RETURN" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected Return: $RETURN"
        echo "   Actual Return: $A_RETURN"
        fails=$fails+1
        return 1
    fi

    # CHECK STDOUT
    local A_STDOUT=$($COMMAND <<< "$STDIN" 2>/dev/null)

    if [[ "$STDOUT" != "$A_STDOUT" ]] && [[ "$STDERR" != "test" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDOUT: $STDOUT"
        echo "   Actual STDOUT: $A_STDOUT"
        fails=$fails+1
        return 2
    fi
    
    # CHECK STDERR
    local A_STDERR=$($COMMAND <<< "$STDIN" 2>&1 >/dev/null)

    if [[ "$STDERR" != "$A_STDERR" ]] && [[ "$STDERR" != "test" ]] ; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDERR: $STDERR"
        echo "   Actual STDERR: $A_STDERR"
        fails=$fails+1
        return 3
    fi
    
    # SUCCESS
    echo "Test $tc Passed"
    return 0
}
##########################################
# EXAMPLE TEST CASES
##########################################

#Test Case 1: Multi-Line [Failure]
test './playtest -w' 1 '5' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit' 'Error: Incorrect menu selection'

#Test Case 2: Multi-Line [Failure]
test './playtest -w' 1 '1 5' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mSelect Difficulty      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Easy Mode
[34m[2][0m: Medium Mode
[34m[3][0m: Hard Mode
[34m[4][0m: Quit' 'Error: Incorrect menu selection'

#Test Case 3: Multi-Line Long Word Easy Difficulty [Failure]
test './playtest -w' 1 '1 1 longggggggword' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mSelect Difficulty      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Easy Mode
[34m[2][0m: Medium Mode
[34m[3][0m: Hard Mode
[34m[4][0m: Quit
[90m|[0m     [1m[37mLevel 1      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━[0m
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 8
User Guess: Invalid word. Try again.
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 8
User Guess: ' ''

#Test Case 4: Multi-Line Short Word Easy Difficulty [Failure]
test './playtest -w' 1 '1 1 hi' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mSelect Difficulty      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Easy Mode
[34m[2][0m: Medium Mode
[34m[3][0m: Hard Mode
[34m[4][0m: Quit
[90m|[0m     [1m[37mLevel 1      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━[0m
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 8
User Guess: Invalid word. Try again.
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 8
User Guess: ' ''

#Test Case 5: Multi-Line Long Word Medium Difficulty [Failure]
test './playtest -w' 1 '1 2 longggggggggg' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mSelect Difficulty      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Easy Mode
[34m[2][0m: Medium Mode
[34m[3][0m: Hard Mode
[34m[4][0m: Quit
[90m|[0m     [1m[37mLevel 1      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━[0m
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 6
User Guess: Invalid word. Try again.
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 6
User Guess: ' ''

#Test Case 6: Multi-Line Long Word Hard Difficulty [Failure]
test './playtest -w' 1 '1 3 longggggggggg' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mSelect Difficulty      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Easy Mode
[34m[2][0m: Medium Mode
[34m[3][0m: Hard Mode
[34m[4][0m: Quit
[90m|[0m     [1m[37mLevel 1      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━[0m
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 4
User Guess: Invalid word. Try again.
[34m[Level][0m: 1 [90m|[0m [34m[Word Length][0m: 5 [90m|[0m [34m[Attempts Left][0m: 4
User Guess: ' ''

#Test Case 7: Multi-Line Quit [Success]
test './playtest -w' 1 '1 4' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mSelect Difficulty      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Easy Mode
[34m[2][0m: Medium Mode
[34m[3][0m: Hard Mode
[34m[4][0m: Quit
[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
Quitting Game.' ''

#Test Case 8: Multi-Line Quit [Success]
test './playtest -w' 1 '4' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
Quitting Game.' ''

#Test Case : Multi-Line Credits [Success]
test './playtest -w' 1 '2' '[90m|[0m     [1m[37mMain Menu      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
[34m[1][0m: Start Game
[34m[2][0m: View Game Credits
[34m[3][0m: --help
[34m[4][0m: Quit
[90m|[0m     [1m[37mCredits      [0m[90m|[0m
━━━━━━━━━━━━━━━━━━━━━━[0m
Team S.A.M.S:
[34mMichael Mondaini[0m
[34mSriha Kanthasamy[0m
[34mSabrina Leung[0m
[34mAxell Panganiban[0m

[34m[1][0m: Back to Main Menu' ''


#return code
exit $fails



